---
- name: Add the webupd8 APT repository key
  become: yes
  become_method: sudo
  apt_key:
    data: "{{lookup('file', 'webupd8.key.asc')}}"
    state: present

- name: Add apt-key
  become: yes
  become_method: sudo
  apt_key: 
    id: "EEA14886"
    keyserver: "hkp://keyserver.ubuntu.com:80"

- name: Add the webupd8 APT repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: "deb {{webupd8_repo_url}} {{ansible_distribution_release|lower}} main"
    state: present
